_veh = _this select 0;

_veh addItemCargoGlobal ["BWA3_RGW90_Loaded",2];
_veh addItemCargoGlobal ["ACE_tourniquet",8];
_veh addItemCargoGlobal ["ACE_fieldDressing",25];
_veh addItemCargoGlobal ["ACE_elasticBandage",25];
_veh addItemCargoGlobal ["ACE_packingBandage",25];
_veh addItemCargoGlobal ["ACE_quikclot",25];
_veh addItemCargoGlobal ["ACE_morphine",15];
_veh addItemCargoGlobal ["ACE_epinephrine",15];
_veh addItemCargoGlobal ["ACE_EarPlugs",5];
_veh addItemCargoGlobal ["BWA3_DM51A1",15];
_veh addItemCargoGlobal ["BWA3_DM25",15];
_veh addItemCargoGlobal ["rhssaf_30rnd_556x45_EPR_G36",20];
_veh addItemCargoGlobal ["rhssaf_30rnd_556x45_Tracers_G36",10];
_veh addItemCargoGlobal ["BWA3_200Rnd_556x45",8];
_veh addItemCargoGlobal ["BWA3_200Rnd_556x45_Tracer",4];
_veh addItemCargoGlobal ["BWA3_10Rnd_762x51_G28",10];
_veh addItemCargoGlobal ["mkk_pzf3_tandem",4];
_veh addItemCargoGlobal ["rhs_mag_M441_HE",25];
_veh addItemcargoGlobal ["rhs_mag_M433_HEDP",10];
_veh addItemcargoGlobal ["1Rnd_Smoke_Grenade_shell",5];
_veh addBackpackCargoGlobal ["BWA3_Kitbag_Tropen",2];
_veh addItemCargoGlobal ["ToolKit",1];
