_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rshg2", 1];
_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",15];
_veh addItemCargoGlobal ["rhs_mag_rgd5",15];
_veh addItemCargoGlobal ["rhs_VOG25",20];
_veh addItemCargoGlobal ["rhs_GRD40_White",10];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7n10_AK",30];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_green",15];
_veh addItemCargoGlobal ["mkk_VTN_RPK74_45p_SC",10];
_veh addItemCargoGlobal ["mkk_VTN_RPK74_45p_TRC",10];
_veh addItemCargoGlobal ["rhs_rpg7_PG7VL_mag",3];
_veh addItemCargoGlobal ["rhs_rpg7_OG7V_mag",3];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];