_veh = _this select 0;

_veh addItemCargoGlobal ["rhs_weap_rpg26",2];
_veh addItemCargoGlobal ["rhs_weap_rshg2",2];
_veh addItemCargoGlobal ["rhs_mag_rgd5",20];
_veh addItemCargoGlobal ["rhs_mag_rdg2_black",20];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_89",25];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_bakelite_tracer",12];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",10];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemCargoGlobal ["rhs_VOG25",30];
_veh addItemCargoGlobal ["rhs_VOG25P",15];
_veh addItemCargoGlobal ["rhs_GDM40",10];
_veh addItemCargoGlobal ["vtn_pg7vm",3];
_veh addItemCargoGlobal ["vtn_og7v",3];
_veh addItemCargoGlobal ["vtn_tbg7v",2];
_veh addItemCargoGlobal ["vtn_pg7vr",3];
_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["ACE_fieldDressing",15];
_veh addItemCargoGlobal ["ACE_elasticBandage",15];
_veh addItemCargoGlobal ["ACE_packingBandage",15];
_veh addItemCargoGlobal ["ACE_quikclot",15];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["H_Cap_oli_hs",2];