_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",12];
_veh addItemcargoGlobal ["ACE_epinephrine",12];
_veh addItemcargoGlobal ["ACE_fieldDressing",20]; 
_veh addItemcargoGlobal ["ACE_tourniquet",4]; 
_veh addItemcargoGlobal ["ACE_quikclot",10];
_veh addItemcargoGlobal ["ACE_elasticBandage",10];
_veh addItemcargoGlobal ["ACE_packingBandage", 10];
_veh addItemcargoGlobal ["rhs_30Rnd_545x39_7N6M_AK", 10];
_veh addItemcargoGlobal ["rhs_100Rnd_762x54mmR", 5];
_veh addItemcargoGlobal ["rhs_10Rnd_762x54mmR_7N14", 10];
_veh addItemcargoGlobal ["rhs_VOG25", 20];
_veh addBackpackcargoglobal ["B_Parachute", 9];
