_veh = _this select 0;

_veh addItemCargoGlobal ["BWA3_RGW90_Loaded",1];
_veh addItemCargoGlobal ["HandGrenade",15];
_veh addItemCargoGlobal ["SmokeShell",15];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",25];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",12];
_veh addItemCargoGlobal ["rhsusf_200Rnd_556x45_box",5];
_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["ACE_fieldDressing",20];
_veh addItemCargoGlobal ["ACE_elasticBandage",20];
_veh addItemCargoGlobal ["ACE_packingBandage",20];
_veh addItemCargoGlobal ["ACE_quikclot",20];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["rhs_mag_maaws_HEAT",4];
_veh addItemCargoGlobal ["rhs_mag_maaws_HE",2];
_veh addbackpackcargoglobal ["BWA3_Kitbag_Tropen",2];
_veh addItemCargoGlobal ["ToolKit",1];
_veh addItemCargoGlobal ["mkk_ffp_m05s_helmet_glasses",2];