_veh = _this select 0;

_veh addItemCargoGlobal ["ace_mag_100rnd_127x99_mag_Tracer_Red",8];
_veh addItemCargoGlobal ["ACE_tourniquet",15];
_veh addItemCargoGlobal ["ACE_fieldDressing",20];
_veh addItemCargoGlobal ["ACE_elasticBandage",20];
_veh addItemCargoGlobal ["ACE_packingBandage",20];
_veh addItemCargoGlobal ["ACE_quikclot",20];
_veh addItemCargoGlobal ["ACE_morphine",20];
_veh addItemCargoGlobal ["ACE_epinephrine",20];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",30];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull_Tracer_Red", 20];
_veh addItemCargoGlobal ["rhs_weap_M136",3];
_veh addItemCargoGlobal ["rhs_mag_f1",12];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",12];
_veh addItemCargoGlobal ["rhs_mag_M441_HE",8];
_veh addItemCargoGlobal ["rhs_mag_M433_HEDP",5];
_veh addItemCargoGlobal ["rhs_mag_m714_White",8];
_veh addItemCargoGlobal ["rhsusf_20Rnd_762x51_m118_special_Mag",7];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",3];
