_veh = _this select 0;

_veh addWeaponCargoGlobal ["rhs_weap_m72a7",2];
_veh addItemCargoGlobal ["rhsgref_30rnd_556x45_vhs2",20];
_veh addItemCargoGlobal ["rhsgref_30rnd_556x45_vhs2_t",10];
_veh addItemCargoGlobal ["rhs_mag_smaw_HEAA",3];
_veh addItemCargoGlobal ["rhs_mag_smaw_HEDP",3];
_veh addItemCargoGlobal ["rhsusf_50Rnd_762x51_m80a1epr",4];
_veh addItemCargoGlobal ["rhsusf_50Rnd_762x51_m62_tracer",4];
_veh addItemCargoGlobal ["rhs_mag_M441_HE",30];
_veh addItemcargoglobal ["rhs_mag_rgd5",20];
_veh addItemcargoglobal ["rhs_mag_rdg2_white",20];
_veh addItemcargoglobal ["ToolKit",1];
_veh addItemcargoglobal ["ACM_CDF_R_M15_Cover_1",2];
    _veh addItemcargoglobal ["ACE_quikclot", 20]; 
    _veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
    _veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
    _veh addItemcargoglobal ["ACE_epinephrine", 20];
    _veh addItemcargoglobal ["ACE_packingBandage", 20];
    _veh addItemcargoglobal ["ACE_morphine", 10];
    _veh addItemcargoglobal ["ACE_tourniquet", 10];