_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_m80", 1];
_veh addItemCargoGlobal ["rhssaf_mag_brd_m83_blue",15];
_veh addItemCargoGlobal ["rhssaf_mag_br_m75",15];
_veh addItemCargoGlobal ["rhs_VOG25",10];
_veh addItemCargoGlobal ["rhsgref_30rnd_556x45_m21_t",15];
_veh addItemCargoGlobal ["mkk_30rnd_556x45_m856a1_m21",8];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemCargoGlobal ["ACE_salineIV_500",15];
_veh addItemCargoGlobal ["ACE_surgicalKit",3];
_veh addItemCargoGlobal ["ACE_personalAidKit",15];
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];