_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_m80", 2];
_veh addItemCargoGlobal ["rhssaf_mag_brd_m83_blue",20];
_veh addItemCargoGlobal ["rhssaf_mag_br_m75",20];
_veh addItemCargoGlobal ["rhs_VOG25",20];
_veh addItemCargoGlobal ["rhsgref_30rnd_556x45_m21_t",30];
_veh addItemCargoGlobal ["mkk_30rnd_556x45_m856a1_m21",15];
_veh addItemCargoGlobal ["rhssaf_250Rnd_762x54R",3];
_veh addItemCargoGlobal ["rhsgref_10Rnd_792x57_m76",10];
_veh addItemCargoGlobal ["rhssaf_10Rnd_792x57_m76_tracer",5];
_veh addItemCargoGlobal ["rhs_mag_smaw_HEDP",5];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];
_veh addItemCargoGlobal ["rhssaf_helmet_m97_digital",2];
_veh addItemCargoGlobal ["ToolKit",1];