_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addItemCargoGlobal ["SmokeShell",15];
_veh addItemCargoGlobal ["rhs_mag_rgd5",15];
_veh addItemCargoGlobal ["rhs_mag_rgn",15];
_veh addItemCargoGlobal ["rhs_mag_zarya2",15];
_veh addItemCargoGlobal ["rhs_VOG25",10];
_veh addItemCargoGlobal ["rhs_GRD40_White",10];
_veh addItemCargoGlobal ["rhs_60Rnd_545X39_7N22_AK",40];
_veh addItemCargoGlobal ["rhs_60Rnd_545X39_AK_Green",20];
_veh addItemCargoGlobal ["mkk_30rnd_9x39_sr3m_sp6",30];
_veh addItemCargoGlobal ["mkk_10Rnd_93x64",10];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR_7BZ3",10];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];