_veh = _this select 0;
_veh addItemcargoglobal ["ACE_fieldDressing", 30];
_veh addItemcargoglobal ["ACE_elasticBandage", 30];
_veh addItemcargoglobal ["ACE_packingBandage", 30];
_veh addItemcargoglobal ["ACE_quikclot", 50];
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_personalAidKit", 10];
_veh addItemcargoglobal ["rhs_mag_rgd5", 15];
_veh addItemcargoglobal ["rhs_mag_rdg2_white", 15];
_veh addBackpackCargoGlobal ["B_Parachute",5];