_veh = _this select 0;

_veh addItemCargoGlobal ["ACE_tourniquet",6];
_veh addItemCargoGlobal ["ACE_fieldDressing",10];
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_morphine",8];
_veh addItemCargoGlobal ["ACE_epinephrine",8];
_veh addItemCargoGlobal ["ACE_EarPlugs",4];
_veh addItemCargoGlobal ["BWA3_DM51A1",4];
_veh addItemCargoGlobal ["BWA3_DM25",4];
_veh addItemCargoGlobal ["rhssaf_30rnd_556x45_EPR_G36",10];
_veh addItemCargoGlobal ["rhssaf_30rnd_556x45_Tracers_G36",8];
_veh addBackpackCargoGlobal ["BWA3_Kitbag_Fleck",4];
_veh addItemCargoGlobal ["ToolKit",1];
_veh addItemCargoGlobal ["BWA3_M92_Fleck", 4];
_veh addMagazinecargoglobal ["mkk_1Rnd_KE_shells", 12]; 
_veh addMagazinecargoglobal ["mkk_1Rnd_MZ_shells", 8]; 
_veh addMagazinecargoglobal ["mkk_1Rnd_HE_shells", 6]; 
_veh addMagazinecargoglobal ["mkk_Mg3_Mag_1200",4]; 
_veh addMagazinecargoglobal ["mkk_120rnd_762x51", 4];