_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",25];
_veh addItemcargoGlobal ["ACE_epinephrine",25];
_veh addItemcargoGlobal ["ACE_fieldDressing",25]; 
_veh addItemcargoGlobal ["ACE_tourniquet",8];
_veh addItemcargoGlobal ["ACE_suture",5];
_veh addItemcargoGlobal ["ACE_splint",5]; 
_veh addItemcargoGlobal ["ACE_quikclot",25];
_veh addItemcargoGlobal ["ACE_elasticBandage",25];
_veh addItemcargoGlobal ["ACE_packingBandage",25];
_veh addItemcargoGlobal ["ACE_personalAidKit",5];
_veh addItemcargoGlobal ["ACE_surgicalKit",1];
_veh addItemcargoGlobal ["rhs_mag_f1",4];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",4];
_veh addItemcargoGlobal ["rhs_30Rnd_545x39_7N10_AK",8];
_veh addItemcargoGlobal ["rhs_30Rnd_762x39mm_89",8];
_veh addItemcargoGlobal ["ACE_rope6", 1];
_veh addItemcargoGlobal ["ACE_rope12", 1];