_veh = _this select 0;

_veh addItemCargoGlobal ["ACE_tourniquet",5];
_veh addItemCargoGlobal ["ACE_fieldDressing",10];
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_morphine",5];
_veh addItemCargoGlobal ["ACE_epinephrine",5];
_veh addItemCargoGlobal ["ACE_splint",8];
_veh addItemCargoGlobal ["ACE_suture",8];
_veh addItemCargoGlobal ["rhs_VOG25",5];
_veh addItemcargoGlobal ["rhs_30Rnd_762x39mm",5];
_veh addItemcargoGlobal ["mkk_20rnd_762x51_M80_G3",5];
_veh addItemcargoGlobal ["mkk_VTN_RPK_40b_SC",5];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",5];
_veh addItemcargoGlobal ["rhs_weap_rpg26",1];
_veh addItemcargoGlobal ["ace_mag_127x108mm_50",6];
_veh addItemCargoGlobal ["rhs_mag_rgn",3];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",3];