_veh = _this select 0;

_veh addItemCargoGlobal ["ACE_tourniquet",5];
_veh addItemCargoGlobal ["ACE_fieldDressing",10];
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_morphine",5];
_veh addItemCargoGlobal ["ACE_epinephrine",5];
_veh addItemCargoGlobal ["ACE_splint",8];
_veh addItemCargoGlobal ["ACE_suture",8];
_veh addItemCargoGlobal ["rhs_VOG25",15];
_veh addItemcargoGlobal ["rhs_30Rnd_762x39mm",15];
_veh addItemcargoGlobal ["mkk_20rnd_762x51_M80_G3",10];
_veh addItemcargoGlobal ["mkk_VTN_RPK_40b_SC",10];
_veh addItemcargoGlobal ["vtn_og7v",2];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",10];
_veh addItemcargoGlobal ["rhs_weap_rpg26",2];
_veh addItemCargoGlobal ["rhs_mag_rgn",8];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",7];