_veh = _this select 0;

_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["ACE_fieldDressing",25];
_veh addItemCargoGlobal ["ACE_elasticBandage",25];
_veh addItemCargoGlobal ["ACE_packingBandage",25];
_veh addItemCargoGlobal ["ACE_quikclot",25];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",5];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_89",30];
_veh addItemcargoGlobal ["rhs_30Rnd_762x39mm_tracer",10];
_veh addItemcargoGlobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemCargoGlobal ["rhs_mag_rgd5",15];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",15];
_veh addItemCargoGlobal ["rhssaf_helmet_m97_olive_nocamo_black_ess",2];
_veh addItemcargoGlobal ["ACE_bloodIV", 7];
_veh addItemcargoGlobal ["ACE_bloodIV_500", 7];
_veh addItemcargoGlobal ["ACE_bloodIV_250", 7];
_veh addItemcargoGlobal ["ACE_personalAidKit", 7];
_veh addItemcargoGlobal ["ACE_surgicalKit", 5];