_veh = _this select 0;

_veh addItemCargoGlobal ["rhs_weap_M136",1];
_veh addItemCargoGlobal ["ACE_tourniquet",8];
_veh addItemCargoGlobal ["ACE_fieldDressing",15];
_veh addItemCargoGlobal ["ACE_elasticBandage",15];
_veh addItemCargoGlobal ["ACE_packingBandage",15];
_veh addItemCargoGlobal ["ACE_quikclot",15];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",8];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan",15];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red", 8];
_veh addItemCargoGlobal ["rhsusf_200Rnd_556x45_soft_pouch_coyote",3];
_veh addItemCargoGlobal ["rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",6];
_veh addItemCargoGlobal ["rhsusf_20Rnd_762x51_SR25_m62_Mag",3];
_veh addItemCargoGlobal ["DemoCharge_Remote_Mag",2];
_veh addItemCargoGlobal ["rhs_mag_m67",10];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",8];
_veh addItemCargoGlobal ["rhs_mag_mk84",8];
_veh addItemCargoGlobal ["rhs_mag_m18_purple",8];
_veh addItemCargoGlobal ["rhs_mag_m18_red",8];
_veh addBackpackCargoGlobal ["B_Parachute",6];