_veh = _this select 0;

_veh addItemcargoglobal ["ACE_morphine", 5]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 10]; 
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_epinephrine",5];
_veh addItemcargoglobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag", 15]; 
_veh addItemcargoglobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", 10]; 
_veh addItemcargoglobal ["rhs_100Rnd_762x54mmR", 5];  
_veh addItemcargoglobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemcargoglobal ["rhs_mag_M441_HE", 16]; 
_veh addItemcargoglobal ["rhs_mag_m714_White", 8]; 
_veh addItemcargoglobal ["rhs_mag_M585_white", 8];
_veh addItemcargoglobal ["rhs_mag_m67", 10];  
_veh addItemcargoglobal ["rhs_mag_rdg2_white", 10];  
_veh addItemcargoglobal ["rhs_rpg7_PG7VL_mag", 3]; 
_veh addWeaponcargoGlobal ["rhs_weap_rpg26", 2];
_veh addBackpackCargoGlobal ["rhsusf_falconii", 2];