_veh = _this select 0;

_veh addItemCargoGlobal ["rhs_weap_rpg26",1];
_veh addItemCargoGlobal ["rhs_mag_rgd5",10];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",10];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7N10_AK",15];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_plum_green",7];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",4];
_veh addItemCargoGlobal ["rhs_VOG25",10];
_veh addItemCargoGlobal ["rhs_GRD40_White",6];
_veh addItemCargoGlobal ["rhs_rpg7_PG7VL_mag",2];
_veh addItemCargoGlobal ["rhs_rpg7_OG7V_mag",2];
_veh addItemCargoGlobal ["ACE_tourniquet",8];
_veh addItemCargoGlobal ["ACE_fieldDressing",12];
_veh addItemCargoGlobal ["ACE_elasticBandage",12];
_veh addItemCargoGlobal ["ACE_packingBandage",12];
_veh addItemCargoGlobal ["ACE_quikclot",12];
_veh addItemCargoGlobal ["ACE_morphine",8];
_veh addItemCargoGlobal ["ACE_epinephrine",8];
_veh addbackpackcargoglobal ["rhs_assault_umbts",2];