_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_m136_HEDP", 2];
_veh addWeaponcargoglobal ["rhs_weap_M136", 2];
_veh addWeaponcargoglobal ["rhs_weap_m32", 1];
_veh addItemCargoGlobal ["MKK_20Rnd_Fury",20];
_veh addItemCargoGlobal ["MKK_20Rnd_Fury_RT",10];
_veh addItemCargoGlobal ["rhsusf_50Rnd_762x51_m80a1epr",5];
_veh addItemCargoGlobal ["MKK_100Rnd_Fury",5];
_veh addItemCargoGlobal ["rhsusf_mag_6Rnd_M441_HE",7];
_veh addItemCargoGlobal ["rhs_mag_M441_HE",10];
_veh addItemcargoglobal ["rhs_mag_m67",10];
_veh addItemcargoglobal ["rhs_mag_an_m8hc",10];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 10];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemcargoglobal ["ACE_splint", 8];
_veh addItemCargoGlobal ["ACE_salineIV_500",5];
_veh addItemCargoGlobal ["ACE_suture",6];
