_veh = _this select 0;

_veh addItemCargoGlobal ["ACE_tourniquet",15];
_veh addItemcargoglobal ["ACE_splint",15]; 
_veh addItemCargoGlobal ["ACE_salineIV_500",15];
_veh addItemCargoGlobal ["ACE_salineIV",15];
_veh addItemCargoGlobal ["ACE_plasmaIV_500",15];
_veh addItemCargoGlobal ["ACE_plasmaIV",15];
_veh addItemCargoGlobal ["ACE_bloodIV_500",15];
_veh addItemCargoGlobal ["ACE_bloodIV",15];
_veh addItemCargoGlobal ["ACE_packingBandage",25];
_veh addItemCargoGlobal ["ACE_fieldDressing",25];
_veh addItemCargoGlobal ["ACE_elasticBandage",25];
_veh addItemCargoGlobal ["ACE_quikclot",25];
_veh addItemCargoGlobal ["ACE_epinephrine",15];
_veh addItemCargoGlobal ["ACE_adenosine",15];
_veh addItemCargoGlobal ["ACE_personalAidKit",15];
_veh addItemcargoglobal ["ACE_suture",15]; 
_veh addItemCargoGlobal ["ACE_surgicalKit",2];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",15];