_veh = _this select 0;

_veh addItemcargoglobal ["ACE_morphine", 10]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 10]; 
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",15];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",10];
_veh addItemcargoGlobal ["rhs_200rnd_556x45_B_SAW",6];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_Mk262_Stanag",5];
_veh addItemcargoGlobal ["rhs_mag_m67",10];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",15];
_veh addItemcargoGlobal ["rhs_mag_M433_HEDP",16];
_veh addItemcargoGlobal ["rhs_mag_M585_white", 8];
_veh addItemcargoGlobal ["rhs_mag_m662_red", 4];
_veh addItemcargoGlobal ["rhs_mag_m661_green", 4];
_veh addItemcargoGlobal ["rhs_mag_M714_white",10];
_veh addItemcargoGlobal ["rhs_weap_M136",1];
_veh addItemcargoGlobal ["ace_mag_100rnd_127x99_mag_Tracer_Red",8];