_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rpg26", 2];
_veh addWeaponcargoglobal ["rhs_weap_rshg2", 2];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_89",30];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_bakelite_tracer",15];
_veh addItemcargoglobal ["rhs_mag_rgd5",20];
_veh addItemcargoglobal ["rhs_mag_rdg2_white",20];
_veh addItemcargoglobal ["rhs_75Rnd_762x39mm_89",3];
_veh addItemcargoglobal ["rhs_75Rnd_762x39mm_tracer",1];
_veh addItemcargoglobal ["rhs_100Rnd_762x54mmR",4];
_veh addItemcargoglobal ["vtn_f7",4];
_veh addItemcargoglobal ["vtn_pg7v",4];
_veh addItemcargoglobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 10];
_veh addItemcargoglobal ["ACE_tourniquet", 10];