_veh = _this select 0;
_veh addItemCargoGlobal ["rhs_weap_M136_hedp",1];
_veh addItemCargoGlobal ["ACE_packingBandage",16];
_veh addItemCargoGlobal ["ACE_elasticBandage",16];
_veh addItemCargoGlobal ["ACE_quikclot",16];
_veh addItemCargoGlobal ["ACE_morphine",16];
_veh addItemCargoGlobal ["ACE_epinephrine",16];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",10];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",25];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",6];
_veh addItemCargoGlobal ["rhs_mag_M441_HE",15];
_veh addItemCargoGlobal ["rhs_mag_m67",6];