_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_7N10_AK", 10];
		_veh addMagazineCargoGlobal ["rhs_mag_rgd5", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_rdg2_white", 5];
		_veh addBackpackCargoGlobal ["B_TacticalPack_oli", 3];
		_veh addItemcargoglobal ["ToolKit", 1];
		_veh addItemCargoGlobal ["ACE_fieldDressing",6];
		_veh addItemCargoGlobal ["ACE_quikclot",6];
		_veh addItemCargoGlobal ["ACE_elasticBandage",6];
		_veh addItemCargoGlobal ["ACE_packingBandage",6];
		_veh addItemCargoGlobal ["ACE_tourniquet",3];
		_veh addItemCargoGlobal ["ACE_morphine",6];
		_veh addItemCargoGlobal ["ACE_epinephrine",6];
		_veh addItemCargoGlobal ["rhs_6b7_1m",3];