_veh = _this select 0;
_veh addItemcargoglobal ["ACE_fieldDressing",20]; 
_veh addItemCargoGlobal ["ACE_elasticBandage",20];
_veh addItemCargoGlobal ["ACE_packingBandage",20];
_veh addItemCargoGlobal ["ACE_quikclot",20];
_veh addItemcargoglobal ["ACE_morphine",10]; 
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["mkk_30Rnd_545x39_7N10_AK_bak",10];
_veh addItemcargoglobal ["rhs_mag_rgd5",8]; 
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",8];
_veh addItemCargoGlobal ["rhs_VOG25",8];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemCargoGlobal ["rhs_weap_rpg26",2];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR_green",5];