_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addWeaponcargoglobal ["rhs_weap_rshg2", 1];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",10];
_veh addItemCargoGlobal ["rhs_mag_f1",10];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_polymer",15];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_bakelite_tracer",6];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7N10_AK",16];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_green",6];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemcargoglobal ["rhs_mine_ozm72_a_mag", 4];
_veh addItemcargoglobal ["rhs_mine_pmn2_mag", 6];
_veh addItemcargoglobal ["rhs_mag_mine_pfm1", 2];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",10];
	_veh addItemCargoGlobal ["ACE_splint",15];
	_veh addItemCargoGlobal ["ACE_bloodIV_500",8];
	_veh addItemCargoGlobal ["ACE_salineIV_500",8];
