_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",15];
_veh addItemCargoGlobal ["rhs_mag_rgd5",15]; 
_veh addItemCargoGlobal ["rhs_VOG25",20];
_veh addItemCargoGlobal ["rhs_GRD40_White",10];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7n10_AK",15];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_green",15];
_veh addItemCargoGlobal ["ToolKit",1];
_veh addBackpackCargoGlobal ["YuE_6sh92rOl",2];
_veh addItemCargoGlobal ["rhs_6b28_green",2];
_veh addItemcargoglobal ["ACE_quikclot", 15]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 15]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 15]; 
_veh addItemcargoglobal ["ACE_epinephrine", 7];
_veh addItemcargoglobal ["ACE_packingBandage", 15];
_veh addItemcargoglobal ["ACE_morphine", 7];
_veh removeMagazinesTurret ["rhs_mag_9m113",[0,0]];
_veh addMagazineTurret ["rhs_mag_9m113",[0,0]];
_veh addMagazineTurret ["rhs_mag_9m113",[0,0]];