_veh = _this select 0;

_veh addItemcargoglobal ["rhs_mag_rgd5", 10];  
_veh addItemcargoglobal ["rhs_mag_rdg2_white", 10]; 
_veh addItemcargoglobal ["rhs_VOG25", 10];
 _veh addWeaponcargoGlobal ["rhs_weap_rpg26", 1];
_veh addItemcargoGlobal ["rhs_30Rnd_545x39_7n10_AK",10];
_veh addItemcargoGlobal ["rhs_30Rnd_545x39_AK_plum_green",5];
_veh addItemCargoGlobal ["ACE_fieldDressing",30];
_veh addItemCargoGlobal ["ACE_elasticBandage",30];
_veh addItemCargoGlobal ["ACE_packingBandage",30];
_veh addItemCargoGlobal ["ACE_quikclot",30];
_veh addItemCargoGlobal ["ACE_morphine",30];
_veh addItemCargoGlobal ["ACE_atropine",30];
_veh addItemCargoGlobal ["ACE_epinephrine",25];
_veh addItemCargoGlobal ["ACE_bloodIV_500",15];
_veh addItemCargoGlobal ["ACE_salineIV_500",15];
_veh addItemCargoGlobal ["ACE_tourniquet",15];
_veh addItemCargoGlobal ["ACE_personalAidKit",10];
_veh addItemCargoGlobal ["ACE_surgicalKit",1];