_veh = _this select 0;
_veh addItemCargoGlobal ["ACE_packingBandage",6];
_veh addItemCargoGlobal ["ACE_elasticBandage",6];
_veh addItemCargoGlobal ["ACE_quikclot",6];
_veh addItemCargoGlobal ["ACE_morphine",6];
_veh addItemCargoGlobal ["ACE_epinephrine",6];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",5];
_veh addItemCargoGlobal ["mkk_20Rnd_762x51_m80a1_Mag",5];
_veh addItemCargoGlobal ["rhsusf_20Rnd_762x51_m993_Mag",2];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",6];
_veh addItemCargoGlobal ["rhs_mag_m67",6];