_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",12];
_veh addItemcargoGlobal ["ACE_epinephrine",12];
_veh addItemcargoGlobal ["ACE_fieldDressing",12]; 
_veh addItemcargoGlobal ["ACE_tourniquet",12]; 
_veh addItemcargoGlobal ["ACE_quikclot",12];
_veh addItemcargoGlobal ["ACE_elasticBandage",12];
_veh addItemcargoGlobal ["ACE_packingBandage", 12];
_veh addItemcargoGlobal ["ACE_personalAidKit",12];
_veh addItemcargoGlobal ["ACE_surgicalKit",12];
_veh addItemcargoGlobal ["mkk_20rnd_762x51_M61_G3",12];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",12];
_veh addItemcargoGlobal ["nmg_96Rnd_545x39_7N10_RPK16",5];
_veh addItemcargoGlobal ["mkk_hlc_20Rnd_762x51_mk316_fal",12];
_veh addItemcargoGlobal ["ace_mag_PG9V",10];
_veh addItemcargoGlobal ["ace_mag_OG9V",10];