_veh = _this select 0;
	_veh addItemCargoGlobal ["ACE_fieldDressing",30];	
	_veh addItemCargoGlobal ["ACE_elasticBandage",30];
	_veh addItemCargoGlobal ["ACE_packingBandage",30];
	_veh addItemCargoGlobal ["ACE_quikclot",30];
	_veh addItemCargoGlobal ["ACE_epinephrine",30];
	_veh addItemCargoGlobal ["ACE_morphine",30];
	_veh addItemCargoGlobal ["ACE_salineIV_500",15];
	_veh addItemCargoGlobal ["ACE_surgicalKit",5];
	_veh addItemCargoGlobal ["ACE_personalAidKit",15];