_veh = _this select 0;

_veh addItemCargoGlobal ["rhs_weap_m72a7",1];
_veh addItemCargoGlobal ["ACE_tourniquet",5];
_veh addItemCargoGlobal ["ACE_fieldDressing",10];
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_morphine",5];
_veh addItemCargoGlobal ["ACE_epinephrine",5];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",10];
_veh addItemcargoGlobal ["mkk_20Rnd_762x51_m80a1_Mag",10];
_veh addItemcargoGlobal ["rhs_30Rnd_545x39_7N10_AK",20];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",10];
_veh addItemCargoGlobal ["rhs_mag_f1",10];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",10];
_veh addItemCargoGlobal ["rhs_VOG25",10];
_veh addBackpackCargoGlobal ["LOP_B_FP_MG42_tub",1];
_veh addItemCargoGlobal ["H_Booniehat_mgrn",2];
_veh addItemCargoGlobal ["ace_mag_145x115mm_50",5];
