_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_m136_HEDP", 2];
_veh addItemCargoGlobal ["rhs_mag_maaws_HEDP", 1];
_veh addItemCargoGlobal ["rhs_mag_maaws_HE", 1];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG",20];
_veh addItemCargoGlobal ["rhs_mag_100Rnd_556x45_M855A1_cmag",10];
_veh addItemCargoGlobal ["rhs_mag_30rnd_556x45_M855A1_PMAG_Tracer_Red",10];
_veh addItemCargoGlobal ["rhs_mag_30rnd_556x45_Mk318_PMAG",10];
_veh addItemcargoglobal ["rhs_mag_m67",10];
_veh addItemcargoglobal ["rhs_mag_an_m8hc",10];
_veh addItemcargoglobal ["rhsusf_200rnd_556x45_mixed_box",10];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 10];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemcargoglobal ["ACE_splint", 10];