_veh = _this select 0;

_veh addWeaponcargoglobal ["mkk_rhs_weap_strela2m", 1];
_veh addItemCargoGlobal ["mkk_rhs_mag_9k32M_rocket",2];
_veh addItemCargoGlobal ["ACE_MX2A",3];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",10];
_veh addItemCargoGlobal ["rhs_mag_f1",30];
_veh addItemCargoGlobal ["rhs_VOG25",15];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7N10_plum_AK",15];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_green",8];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];
_veh addItemCargoGlobal ["ACE_UAVBattery",6];