_veh = _this select 0;

_veh addItemCargoGlobal ["rhs_weap_rpg26", 2];
_veh addItemCargoGlobal ["ACE_tourniquet",15];
_veh addItemCargoGlobal ["ACE_fieldDressing",15];
_veh addItemCargoGlobal ["ACE_elasticBandage",15];
_veh addItemCargoGlobal ["ACE_packingBandage",15];
_veh addItemCargoGlobal ["ACE_quikclot",15];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["ACE_EarPlugs",2];
_veh addItemCargoGlobal ["rhs_mag_rgd5",8];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",8];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",12];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",7];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",5];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",8];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_89",10];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_plum_green",6];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7N10_AK",15];
_veh addItemCargoGlobal ["rhs_45Rnd_545X39_7N10_AK",4];
_veh addItemCargoGlobal ["rhs_rpg7_PG7VL_mag",3];
_veh addItemCargoGlobal ["rhs_rpg7_OG7V_mag",1];
_veh addItemCargoGlobal ["rhs_VOG25",25];
_veh addItemCargoGlobal ["ACE_personalAidKit",3];
_veh addItemCargoGlobal ["ACE_surgicalKit",1];
_veh addbackpackcargoglobal ["B_AssaultPack_blk",3];

_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];