_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_M136", 1];
_veh addItemCargoGlobal ["mkk_20rnd_762x51_M61_G3",5];
_veh addItemCargoGlobal ["BWA3_DM51A1",15];
_veh addItemCargoGlobal ["BWA3_DM25",15];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",20];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull_Tracer_Red",10];
_veh addItemCargoGlobal ["rhsusf_100Rnd_762x51_m80a1epr",5];
_veh addItemCargoGlobal ["rhsusf_200rnd_556x45_mixed_box",5];
_veh addItemCargoGlobal ["rhs_mag_M441_HE",20];
_veh addItemCargoGlobal ["rhs_mag_maaws_HEDP",3];
_veh addItemCargoGlobal ["rhs_mag_maaws_HEAT",3];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];