_veh = _this select 0;

_veh addItemCargoGlobal ["rhsusf_mich_helmet_marpatd_alt",2];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",10];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_EPM_Tracer_Red",4];
_veh addItemCargoGlobal ["rhs_mag_m67",10];
_veh addItemCargoGlobal ["rhs_mag_m18_green",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_quikclot",20];
_veh additemcargoGlobal ["ACE_fieldDressing",20];
_veh addItemCargoGlobal ["ACE_elasticBandage",20];
_veh addItemCargoGlobal ["ACE_packingBandage",20];
_veh addItemCargoGlobal ["ACE_salineIV_500",15];
_veh addItemCargoGlobal ["ACE_surgicalKit",3];
_veh addItemCargoGlobal ["ACE_personalAidKit",15];
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];
_veh addItemCargoGlobal ["ToolKit",1];