_veh = _this select 0;

_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_polymer",10];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_polymer_tracer",5];
_veh addItemCargoGlobal ["rhs_mag_rgd5",10];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",10];
_veh addItemCargoGlobal ["ACE_fieldDressing",15];		
_veh addItemCargoGlobal ["ACE_elasticBandage",15];
_veh addItemCargoGlobal ["ACE_packingBandage",15];
_veh addItemCargoGlobal ["ACE_quikclot",15];
_veh addItemCargoGlobal ["ACE_epinephrine",15];
_veh addItemCargoGlobal ["ACE_morphine",15];
_veh addItemCargoGlobal ["ace_mag_100rnd_127x99_mag_Tracer_Red",10];
_veh addItemCargoGlobal ["mkk_mag_M1069",12];
_veh addItemCargoGlobal ["mkk_mag_M829A3",14];
_veh addItemCargoGlobal ["mkk_mag_M830A1",10];
_veh addItemCargoGlobal ["rhsusf_100Rnd_762x51_m80a1epr",20];
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];
_veh addItemCargoGlobal ["rhsusf_ach_helmet_DCU_early",4];
_veh addItemCargoGlobal ["ToolKit",1];