_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",15];
_veh addItemCargoGlobal ["rhs_mag_rgd5",15];
_veh addItemCargoGlobal ["rhs_VOG25",20];
_veh addItemCargoGlobal ["rhs_GRD40_White",10];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7N22_AK",30];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_green",15];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR_7BZ3",5];
_veh addItemCargoGlobal ["mkk_30rnd_9x39_sr3m_sp6",20];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemcargoglobal ["ACE_splint", 8];