_this addWeaponCargoGlobal ["rhs_weap_m72a7",1];
_this addItemCargoGlobal ["rhsgref_30rnd_556x45_vhs2",20];
_this addItemCargoGlobal ["rhsgref_30rnd_556x45_vhs2_t",10];
_this addItemCargoGlobal ["rhs_mag_smaw_HEAA",2];
_this addItemCargoGlobal ["rhs_mag_smaw_HEDP",2];
_this addItemCargoGlobal ["rhsusf_50Rnd_762x51_m80a1epr",4];
_this addItemCargoGlobal ["rhsusf_50Rnd_762x51_m62_tracer",4];
_this addItemCargoGlobal ["rhs_mag_M441_HE",30];
_this addItemcargoglobal ["rhs_mag_rgd5",20];
_this addItemcargoglobal ["rhs_mag_rdg2_white",20];
_this addItemcargoglobal ["ToolKit",1];
_this addItemcargoglobal ["ACM_CDF_R_M15_Cover_1",2];
_this addItemcargoglobal ["ACE_quikclot", 20]; 
_this addItemcargoglobal ["ACE_elasticBandage", 20]; 
_this addItemcargoglobal ["ACE_fieldDressing", 20]; 
_this addItemcargoglobal ["ACE_epinephrine", 20];
_this addItemcargoglobal ["ACE_packingBandage", 20];
_this addItemcargoglobal ["ACE_morphine", 10];
_this addItemcargoglobal ["ACE_tourniquet", 10];

_this addItemCargoGlobal ["ace_mag_9m113m",2];