_veh = _this select 0;
_veh additemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",20];
_veh additemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",10];
_veh additemcargoGlobal ["rhs_mag_m67",10];
_veh additemcargoGlobal ["rhs_mag_an_m8hc",10];
_veh addItemCargoGlobal ["ACE_fieldDressing",10];
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh additemcargoGlobal ["ACE_tourniquet",10];
_veh additemcargoGlobal ["rhsusf_100Rnd_762x51_m80a1epr",10];
_veh additemcargoGlobal ["rhs_mag_maaws_HEAT",4];
_veh additemcargoGlobal ["rhs_mag_maaws_HE",4];
_veh additemcargoGlobal ["mkk_20Rnd_762x51_m80_Mag", 10];
_veh addItemCargoGlobal ["ACE_splint",10];