_this = _this select 0;

_this addWeaponCargoGlobal ["mkk_rhs_weap_fim92a",1];
_this addItemCargoGlobal ["mkk_rhs_fim92A_mag",1];
_this addItemCargoGlobal ["ACE_MX2A",1];
_this addItemCargoGlobal ["rhssaf_30rnd_556x45_EPR_G36",15];
_this addItemCargoGlobal ["rhssaf_30rnd_556x45_Tracers_G36",8];
_this addItemcargoglobal ["BWA3_DM25",15];
_this addItemcargoglobal ["BWA3_DM51A1",15];
    _this addItemcargoglobal ["ACE_quikclot", 20]; 
    _this addItemcargoglobal ["ACE_elasticBandage", 20]; 
    _this addItemcargoglobal ["ACE_fieldDressing", 20]; 
    _this addItemcargoglobal ["ACE_epinephrine", 20];
    _this addItemcargoglobal ["ACE_packingBandage", 20];
    _this addItemcargoglobal ["ACE_morphine", 10];
    _this addItemcargoglobal ["ACE_tourniquet", 10];
    _this addItemCargoGlobal ["ACE_epinephrine",30];
	_this addItemCargoGlobal ["ACE_salineIV_500",15];
	_this addItemCargoGlobal ["ACE_surgicalKit",4];
	_this addItemCargoGlobal ["ACE_personalAidKit",15];