_veh = _this select 0;
_veh addItemCargoGlobal ["rhs_weap_rpg26",2];
_veh addItemCargoGlobal ["ace_mag_VOG30_30",7];
_veh addItemCargoGlobal ["ACE_tourniquet",15];
_veh addItemCargoGlobal ["ACE_fieldDressing",25];
_veh addItemCargoGlobal ["ACE_elasticBandage",25];
_veh addItemCargoGlobal ["ACE_packingBandage",25];
_veh addItemCargoGlobal ["ACE_quikclot",25];
_veh addItemCargoGlobal ["ACE_morphine",20];
_veh addItemCargoGlobal ["ACE_epinephrine",20];
_veh addItemCargoGlobal ["ACE_EarPlugs",4];
_veh addItemCargoGlobal ["rhs_mag_f1",10];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",10];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7N10_AK",15];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_plum_green",10];
_veh addItemCargoGlobal ["rhs_mag_9x19mm_7n31_20",5];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR_7N13",5];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR_green",3];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",8];
_veh addItemCargoGlobal ["rhs_VOG25",18];
_veh addBackpackCargoGlobal ["rhssaf_kitbag_smb", 3];
