_veh = _this select 0;

this disableTIEquipment true;
_veh addItemCargoGlobal ["ACE_tourniquet",8];
_veh addItemCargoGlobal ["ACE_fieldDressing",25];
_veh addItemCargoGlobal ["ACE_elasticBandage",25];
_veh addItemCargoGlobal ["ACE_packingBandage",25];
_veh addItemCargoGlobal ["ACE_quikclot",25];
_veh addItemCargoGlobal ["ACE_morphine",15];
_veh addItemCargoGlobal ["ACE_epinephrine",15];
_veh addItemCargoGlobal ["ACE_EarPlugs",5];
_veh addItemCargoGlobal ["BWA3_DM51A1",15];
_veh addItemCargoGlobal ["BWA3_DM25",15];
_veh addItemCargoGlobal ["rhssaf_30rnd_556x45_EPR_G36",20];
_veh addItemCargoGlobal ["rhssaf_30rnd_556x45_Tracers_G36",10];
_veh addItemCargoGlobal ["BWA3_200Rnd_556x45",8];
_veh addItemCargoGlobal ["BWA3_200Rnd_556x45_Tracer",4];
_veh addItemCargoGlobal ["mkk_pzf3_tandem",2];
_veh addItemCargoGlobal ["mkk_pzf3_dm32",2];
_veh addItemCargoGlobal ["rhs_mag_M441_HE",10];
_veh addItemcargoGlobal ["rhs_mag_M433_HEDP",5];
_veh addBackpackCargoGlobal ["BWA3_Kitbag_Fleck",1];
