_veh = _this select 0;
_veh addItemcargoglobal ["ACE_fieldDressing",20]; 
_veh addItemCargoGlobal ["ACE_elasticBandage",20];
_veh addItemCargoGlobal ["ACE_packingBandage",20];
_veh addItemCargoGlobal ["ACE_quikclot",20];
_veh addItemcargoglobal ["ACE_morphine",10]; 
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm",15];
_veh addItemcargoglobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",10]; 
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",6];
_veh addItemCargoGlobal ["rhs_VOG25",25];
_veh addItemCargoGlobal ["vtn_pg7v",2];
_veh addItemCargoGlobal ["rhs_weap_rpg26",1];
_veh addItemCargoGlobal ["ace_48Rnd_40mm_MK19_M430A1",4];
_veh addItemCargoGlobal ["ACE_EarPlugs ",2];
_veh addItemCargoGlobal ["rhs_mag_m67",10];
_veh addItemCargoGlobal ["SmokeShell",10];
["ACE_Wheel", _veh] call ace_cargo_fnc_loadItem;
["ACE_Wheel", _veh] call ace_cargo_fnc_loadItem;