_veh = _this select 0;
_veh addItemcargoglobal ["ACE_fieldDressing",20]; 
_veh addItemCargoGlobal ["ACE_elasticBandage",20];
_veh addItemCargoGlobal ["ACE_packingBandage",20];
_veh addItemCargoGlobal ["ACE_quikclot",20];
_veh addItemcargoglobal ["ACE_morphine",10]; 
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["rhs_mag_m67",10];
_veh addItemCargoGlobal ["SmokeShell",10];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addBackpackCargoGlobal ["mkk_rt1523g_big_bwmod_tropen_RED",1];
_veh addItemCargoGlobal ["ACE_EarPlugs ",2];