_veh addItemCargoGlobal ["rhs_weap_M136",2];
_veh addItemCargoGlobal ["rhs_weap_M136_hedp",1];
_veh addItemCargoGlobal ["ACE_quikclot",25];
_veh addItemCargoGlobal ["ACE_fieldDressing",25];
_veh addItemCargoGlobal ["ACE_elasticBandage",25];
_veh addItemCargoGlobal ["ACE_packingBandage",25];
_veh addItemCargoGlobal ["ACE_tourniquet",15];
_veh addItemCargoGlobal ["ACE_epinephrine",20];
_veh addItemCargoGlobal ["ACE_morphine",20];
_veh addItemCargoGlobal ["mkk_hlc_30rnd_556x45_EPR_HK33",30];
_veh addItemcargoGlobal ["mkk_30rnd_556x45_M856A1_HK33", 10];
_veh addItemCargoGlobal ["mkk_50Rnd_762x51_M80_MG3_drum",14];
_veh addItemCargoGlobal ["rhs_mag_m67",15];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",15];
_veh addItemCargoGlobal ["ace_48Rnd_40mm_MK19_M430A1",8];
_veh addItemCargoGlobal ["rhs_mag_M441_HE",20];
_veh addItemCargoGlobal ["rhs_mag_m714_White",8];
_veh addItemCargoGlobal ["LOP_B_FP_MG42_tub",2];
