_this addItemCargoGlobal ["rhs_mag_m18_yellow", 10];
_this addItemCargoGlobal ["rhs_mag_m67", 10];
_this addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag", 10];
_this addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M196_Stanag_Tracer_Red",10];
_this addItemCargoGlobal ["rhs_mag_M433_HEDP",10];
_this addItemCargoGlobal ["ACE_fieldDressing",20];
_this addItemCargoGlobal ["ACE_elasticBandage",20];
_this addItemcargoglobal ["ACE_packingBandage",20];
_this addItemcargoglobal ["ACE_quikclot",20];
_this addItemcargoglobal ["ACE_epinephrine",20];
_this addItemcargoglobal ["ACE_morphine", 20]; 
_this addItemcargoglobal ["ACE_surgicalKit", 10]; 
_this addItemcargoglobal ["ACE_personalAidKit", 10];
_this addItemcargoglobal ["mkk_20Rnd_M80_762x51_HK417", 10];
_this addItemcargoglobal ["mkk_20Rnd_M62_762x51_HK417", 10];
