_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",2];
_veh addItemcargoGlobal ["ACE_epinephrine",22];
_veh addItemcargoGlobal ["ACE_fieldDressing",22]; 
_veh addItemcargoGlobal ["ACE_tourniquet",22]; 
_veh addItemcargoGlobal ["ACE_quikclot",22];
_veh addItemcargoGlobal ["ACE_elasticBandage",22];
_veh addItemcargoGlobal ["ACE_packingBandage", 22];
_veh addItemcargoGlobal ["ACE_personalAidKit",8];
_veh addItemcargoGlobal ["rhs_mag_f1",8];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",8];
_veh addItemcargoGlobal ["rhs_30Rnd_545x39_7N10_AK",8];
_veh addItemcargoGlobal ["rhs_30Rnd_762x39mm_89",8];