_this addItemCargoGlobal ["rhssaf_30rnd_556x45_SOST_G36",10];
_this addItemCargoGlobal ["rhssaf_30rnd_556x45_Tracers_G36",5];
_this addItemcargoglobal ["BWA3_DM25",6];
_this addItemcargoglobal ["BWA3_DM51A1",3];
_this addItemcargoglobal ["ACE_quikclot", 20]; 
_this addItemcargoglobal ["ACE_elasticBandage", 20]; 
_this addItemcargoglobal ["ACE_fieldDressing", 20]; 
_this addItemcargoglobal ["ACE_epinephrine", 20];
_this addItemcargoglobal ["ACE_packingBandage", 20];
_this addItemcargoglobal ["ACE_morphine", 10];
_this addItemcargoglobal ["ACE_tourniquet", 10];
_this addItemCargoGlobal ["ACE_epinephrine",30];