_veh = _this select 0;

_veh addItemcargoGlobal ["rhs_weap_M136_hedp",1];
_veh addItemcargoglobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer", 20]; 
_veh addItemcargoglobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", 15]; 
_veh addItemcargoglobal ["rhs_200rnd_556x45_M_SAW", 6];
_veh addItemcargoglobal ["SatchelCharge_Remote_Mag", 8]; 
_veh addMagazinecargoglobal ["rhs_mag_an_m8hc", 15];  
_veh addMagazinecargoglobal ["rhs_mag_m67", 15];
_veh addBackpackCargoGlobal ["rhsusf_assault_eagleaiii_coy", 3];
_veh addItemCargoGlobal ["ACE_fieldDressing",30];
_veh addItemCargoGlobal ["ACE_packingBandage",30];
_veh addItemCargoGlobal ["ACE_elasticBandage",30];
_veh addItemCargoGlobal ["ACE_quikclot",30];
_veh addItemCargoGlobal ["ACE_morphine",20];
_veh addItemCargoGlobal ["ACE_epinephrine",20];
_veh addItemCargoGlobal ["ACE_bloodIV_500",10];
_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["ACE_personalAidKit",15];
_veh addItemCargoGlobal ["ACE_surgicalKit",2];