_veh = _this select 0;

_veh addMagazinecargoglobal ["rhs_mag_M829A3", 22];
_veh addMagazinecargoglobal ["rhs_mag_M830A1", 8];
_veh addMagazinecargoglobal ["rhs_mag_762x51_M240_1200", 8];
_veh addMagazinecargoglobal ["rhs_mag_762x51_M240_200", 9];
_veh addMagazinecargoglobal ["ace_mag_100rnd_127x99_mag_Tracer_Red", 10];
_veh addItemCargoGlobal ["ACE_tourniquet",15];
_veh addItemCargoGlobal ["ACE_fieldDressing",20];
_veh addItemCargoGlobal ["ACE_elasticBandage",20];
_veh addItemCargoGlobal ["ACE_packingBandage",20];
_veh addItemCargoGlobal ["ACE_quikclot",20];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["ACE_EarPlugs",4];
_veh addItemCargoGlobal ["rhs_mag_rgd5",10];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",10];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",10];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",6];
_veh addBackpackCargoGlobal ["BWA3_Kitbag_Tropen",4];
_veh addItemCargoGlobal ["ToolKit",1];
_veh addItemCargoGlobal ["rhssaf_helmet_m97_olive_nocamo", 4];
