_veh = _this select 0;

_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_Mk318_PMAG",20];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",10];
_veh addItemCargoGlobal ["rhsusf_20Rnd_762x51_SR25_m993_Mag",8];
_veh addItemCargoGlobal ["rhs_mag_M397_HET",12];
_veh addItemCargoGlobal ["rhs_mag_M433_HEDP",12];
_veh addItemCargoGlobal ["rhsusf_5Rnd_300winmag_xm2010",20];
_veh addItemCargoGlobal ["rhsusf_20Rnd_762x51_SR25_m993_Mag",10];
_veh addItemCargoGlobal ["Laserbatteries",4];
_veh addItemcargoglobal ["rhs_mag_m67",20];
_veh addItemcargoglobal ["rhs_mag_an_m8hc",20];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 10];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];
_veh addBackpackcargoglobal ["B_Parachute", 14];