_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addWeaponcargoglobal ["mkk_VTN_AKS74U_TUNED", 1];
_veh addItemCargoGlobal ["rhs_acc_pgs64_74u",1];
_veh addItemCargoGlobal ["vtn_optic_eotech_exps3_0b",1];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",15];
_veh addItemCargoGlobal ["rhs_mag_rgd5",15];
_veh addItemCargoGlobal ["rhs_mag_rgn",15];
_veh addItemCargoGlobal ["rhs_VOG25",10];
_veh addItemCargoGlobal ["rhs_VOG25P",5];
_veh addItemCargoGlobal ["rhs_GDM40",5];
_veh addItemCargoGlobal ["ACE_CableTie",16];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_polymer",10];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_polymer_tracer",5];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7N10_plum_AK",10];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_green",5];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",5];
_veh addItemCargoGlobal ["vtn_pg7vm",3];
_veh addItemCargoGlobal ["vtn_og7v",3];
_veh addItemCargoGlobal ["mkk_VTN_TIGR_20s_AP",3];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemcargoglobal ["ace_mag_127x108mm_50", 6];
_veh addItemcargoglobal ["DemoCharge_Remote_Mag", 8];