_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addItemcargoglobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag", 12]; 
_veh addItemcargoglobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", 12];
_veh addItemcargoglobal ["rhs_100Rnd_762x54mmR", 2];
_veh addItemcargoglobal ["rhsusf_20Rnd_762x51_m80_Mag", 4]; 
_veh addItemcargoglobal ["rhs_mag_M441_HE", 5];
_veh addItemcargoglobal ["rhs_rpg7_PG7VL_mag", 2];
_veh addItemcargoglobal ["rhs_rpg7_OG7V_mag", 2];
_veh addItemcargoglobal ["rhs_mag_rgd5", 10];  
_veh addItemcargoglobal ["rhs_mag_rdg2_white", 10];
_veh addItemcargoglobal ["ACE_morphine", 10]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 10]; 
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addBackpackCargoGlobal ["B_TacticalPack_blk", 2];
_veh addItemcargoglobal ["ToolKit", 1];
_veh addItemcargoglobal ["rhsgref_ssh68_ttsko_mountain", 2];