_veh = _this select 0;

_veh addbackpackcargoglobal ["UNS_Alice_2",3];
_veh addItemCargoGlobal ["rhs_weap_M136",2];
_veh addItemCargoGlobal ["rhs_weap_M136_hedp",2];
_veh addItemcargoglobal ["ACE_EarPlugs", 4];
_veh addItemCargoGlobal ["usm_helmet_pasgt_w_m",4];
_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["ACE_fieldDressing",10];
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_morphine",8];
_veh addItemCargoGlobal ["ACE_epinephrine",8];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",10];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", 4];
_veh addItemCargoGlobal ["rhs_mag_m67",4];
_veh addItemCargoGlobal ["rhs_mag_m18_purple",8];
_veh addItemCargoGlobal ["ToolKit",1];								
_veh addItemCargoGlobal ["mkk_mag_M829A3",22];				
_veh addItemCargoGlobal ["mkk_mag_M830A1",10];				
_veh addItemCargoGlobal ["rhsusf_100Rnd_762x51_m80a1epr",5];				
_veh addMagazinecargoglobal ["ace_mag_100rnd_127x99_mag_Tracer_Red", 10];