_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",25];
_veh addItemcargoGlobal ["ACE_epinephrine",25];
_veh addItemcargoGlobal ["ACE_fieldDressing",25]; 
_veh addItemcargoGlobal ["ACE_tourniquet",25];
_veh addItemcargoGlobal ["ACE_suture",2];
_veh addItemcargoGlobal ["ACE_splint",2];
_veh addItemcargoGlobal ["ACE_quikclot",25];
_veh addItemcargoGlobal ["ACE_elasticBandage",25];
_veh addItemcargoGlobal ["ACE_packingBandage", 25];
_veh addItemcargoGlobal ["ACE_personalAidKit",1];
_veh addItemcargoGlobal ["ACE_surgicalKit",1];
_veh addItemcargoGlobal ["rhs_mag_m67",6];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",6];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",12];
_veh addItemcargoGlobal ["mkk_rhs_mag_9k32M_rocket",2];
_veh addItemcargoGlobal ["mkk_rhs_weap_strela2m",1];