_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",3];
_veh addItemcargoGlobal ["ACE_epinephrine",3];
_veh addItemcargoGlobal ["ACE_fieldDressing",6]; 
_veh addItemcargoGlobal ["ACE_tourniquet",3];
_veh addItemcargoGlobal ["ACE_suture",2];
_veh addItemcargoGlobal ["ACE_splint",2];
_veh addItemcargoGlobal ["ACE_quikclot",6];
_veh addItemcargoGlobal ["ACE_elasticBandage",6];
_veh addItemcargoGlobal ["ACE_packingBandage", 6];
_veh addItemcargoGlobal ["rhs_mag_m67",3];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",3];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",6];
_veh addItemcargoGlobal ["ACE_rope6", 1];
_veh addItemcargoGlobal ["ACE_rope12", 1];
_veh addItemcargoGlobal ["mkk_rhs_fim92A_mag", 8];
_veh addItemcargoGlobal ["ace_100rnd_lav_ad", 12];