_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",15];
_veh addItemcargoGlobal ["ACE_epinephrine",15];
_veh addItemcargoGlobal ["ACE_fieldDressing",15]; 
_veh addItemcargoGlobal ["ACE_tourniquet",8]; 
_veh addItemcargoGlobal ["ACE_quikclot",15];
_veh addItemcargoGlobal ["ACE_suture",2];
_veh addItemcargoGlobal ["ACE_splint",2];
_veh addItemcargoGlobal ["ACE_elasticBandage",15];
_veh addItemcargoGlobal ["ACE_packingBandage",15];
_veh addItemcargoGlobal ["ACE_personalAidKit",3];
_veh addItemcargoGlobal ["ACE_surgicalKit",1];
_veh addItemcargoGlobal ["rhs_mag_m67",8];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",8];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",12];
_veh addItemcargoGlobal ["mkk_20Rnd_M80A1_762x51_HK417",10];
_veh addItemcargoGlobal ["rhs_mag_20Rnd_SCAR_762x51_m80a1_epr",10];
_veh addItemcargoGlobal ["rhsusf_200rnd_556x45_mixed_box",6];
_veh addItemcargoGlobal ["rhs_weap_M136",1];
_veh addItemcargoGlobal ["rhs_mag_M433_HEDP",8];
_veh addItemcargoGlobal ["ACE_rope6", 1];
_veh addItemcargoGlobal ["ACE_rope12", 1];
_veh addItemcargoGlobal ["ace_48Rnd_40mm_MK19_M430A1", 4];