_veh = _this select 0;
  
_veh addItemcargoglobal ["rhs_30Rnd_545x39_7N22_AK", 20];
_veh addItemcargoglobal ["rhs_10Rnd_762x54mmR_7N14", 10];  
_veh addItemcargoglobal ["rhs_30Rnd_545x39_AK_green", 10]; 
_veh addItemcargoglobal ["rhs_100Rnd_762x54mmR", 5];  
_veh addMagazinecargoglobal ["rhs_VOG25", 10]; 
_veh addMagazinecargoglobal ["rhs_mag_rgd5", 5];  
_veh addMagazinecargoglobal ["rhs_mag_rdg2_white", 5];  
_veh addItemcargoglobal ["rhs_rpg7_PG7VL_mag", 2]; 
_veh addItemcargoglobal ["rhs_rpg7_OG7V_mag", 2]; 
_veh addBackpackCargoGlobal ["rhs_sidor", 3];
_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addItemCargoGlobal ["rhs_weap_rsp30_white", 10];
_veh addItemcargoglobal ["ToolKit", 1];
_veh addItemcargoGlobal ["ACE_morphine",12];
_veh addItemcargoGlobal ["ACE_epinephrine",12];
_veh addItemcargoGlobal ["ACE_fieldDressing",20]; 
_veh addItemcargoGlobal ["ACE_tourniquet",4]; 
_veh addItemcargoGlobal ["ACE_quikclot",10];
_veh addItemcargoGlobal ["ACE_elasticBandage",10];
_veh addItemcargoGlobal ["ACE_packingBandage", 10];