_this addItemcargoGlobal ["ACE_EarPlugs", 2];
_this addItemcargoglobal ["rhs_mag_rgd5", 15];  
_this addItemcargoglobal ["rhs_mag_rdg2_white", 10];
_this addItemCargoGlobal ["ACE_bloodIV_500",20];
_this addItemCargoGlobal ["ACE_plasmaIV_250",8];
_this addItemCargoGlobal ["ACE_salineIV_250",8];
_this addItemCargoGlobal ["ACE_tourniquet",8];
_this addItemCargoGlobal ["ACE_personalAidKit",20];
_this addItemCargoGlobal ["ACE_surgicalKit",4];
_this addItemcargoglobal ["ACE_morphine", 50]; 
_this addItemcargoglobal ["ACE_fieldDressing", 50]; 
_this addItemCargoGlobal ["ACE_elasticBandage",50];
_this addItemCargoGlobal ["ACE_packingBandage",50];
_this addItemCargoGlobal ["ACE_quikclot",50];
_this addItemCargoGlobal ["ACE_epinephrine",50];
_this addItemCargoGlobal ["ACE_rope6",2];
_this addItemCargoGlobal ["ACE_rope12",2];
_this addItemcargoGlobal ["ACE_suture",5];
_this addItemcargoGlobal ["ACE_splint",5]; 
