_veh = _this select 0;

_veh addWeaponCargoGlobal ["rhs_weap_M136",1];
_veh addWeaponCargoGlobal ["rhs_weap_M136_hedp",1];
_veh addItemCargoGlobal ["rhsusf_mich_helmet_marpatd_alt",2];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",20];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_EPM_Tracer_Red",8];
_veh addItemCargoGlobal ["rhsusf_100Rnd_762x51_m80a1epr",6];
_veh addItemCargoGlobal ["rhs_mag_maaws_HE",2];
_veh addItemCargoGlobal ["rhs_mag_maaws_HEAT",2];
_veh addItemCargoGlobal ["rhs_mag_m67",20];
_veh addItemCargoGlobal ["rhs_mag_m18_green",20];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["ACE_tourniquet",10];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_quikclot",20];
_veh additemcargoGlobal ["ACE_fieldDressing",20];
_veh addItemCargoGlobal ["ACE_elasticBandage",20];
_veh addItemCargoGlobal ["ACE_packingBandage",20];
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];
_veh addItemCargoGlobal ["ToolKit",1];