_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_ak105_zenitco01_b33", 2];
_veh addItemCargoGlobal ["rhsusf_acc_eotech_552",2];
_veh addItemCargoGlobal ["rhs_acc_dtk1",2];
_veh addItemCargoGlobal ["rhs_acc_grip_rk6",2];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",5];
_veh addItemCargoGlobal ["rhs_mag_rgd5",5];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7n22_AK",10];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_green",5];
_veh addItemCargoGlobal ["mkk_5Rnd_127x108_Mag",5];
_veh addItemCargoGlobal ["mkk_5Rnd_127x108_APDS_Mag",2];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
	_veh addItemcargoglobal ["ACE_splint", 10];