_veh = _this select 0;

_veh addItemcargoglobal ["rhs_30Rnd_545x39_7N10_AK", 15]; 
_veh addItemcargoglobal ["rhs_30Rnd_545x39_AK_plum_green", 10];
_veh addItemcargoglobal ["rhs_100Rnd_762x54mmR", 5];
_veh addItemcargoglobal ["rhs_10Rnd_762x54mmR_7N14", 10]; 
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm", 10];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_tracer", 5];
_veh addItemcargoglobal ["rhs_VOG25", 25];
_veh addItemcargoglobal ["rhs_rpg7_PG7VL_mag", 3];
_veh addItemcargoglobal ["rhs_rpg7_OG7V_mag", 3];
_veh addItemcargoglobal ["rhs_mag_rgd5", 10];  
_veh addItemcargoglobal ["rhs_mag_rdg2_white", 10];
_veh addItemcargoglobal ["ACE_morphine", 5]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 15]; 
_veh addItemCargoGlobal ["ACE_elasticBandage",15];
_veh addItemCargoGlobal ["ACE_packingBandage",15];
_veh addItemCargoGlobal ["ACE_quikclot",15];
_veh addItemCargoGlobal ["ACE_epinephrine",5];
_veh addBackpackCargoGlobal ["B_TacticalPack_oli", 2];