_veh = _this select 0;

_veh addItemcargoglobal ["ItemGPS", 1];
_veh addItemCargoGlobal ["mkk_rhs_weap_rpg18", 2];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_7N6M_plum_AK", 20];
_veh addItemCargoGlobal ["rhs_30Rnd_545x39_AK_plum_green", 10];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14", 10];
_veh addItemCargoGlobal ["rhs_45Rnd_545X39_7N6_AK", 10];
_veh addItemCargoGlobal ["rhs_rpg7_PG7VL_mag", 4];
_veh addItemCargoGlobal ["rhs_mag_rgd5", 20];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white", 20];
_veh addItemCargoGlobal ["rhs_VOG25", 15];
_veh addBackpackCargoGlobal ["RD_6B3", 2];
_veh addItemcargoglobal ["rhs_fieldcap_khk", 2];
_veh addItemCargoGlobal ["ACE_fieldDressing",20];
_veh addItemCargoGlobal ["ACE_elasticBandage",20];
_veh addItemCargoGlobal ["ACE_packingBandage",20];
_veh addItemCargoGlobal ["ACE_quikclot",20];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["ACE_tourniquet",10];