_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_M136_hedp", 1];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG",20];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",10];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_Mk262_PMAG",10];
_veh addItemCargoGlobal ["rhs_mag_maaws_HEAT",3];
_veh addItemCargoGlobal ["rhs_mag_maaws_HE",3];
_veh addItemCargoGlobal ["rhs_mag_M441_HE",20];
_veh addItemCargoGlobal ["rhs_mag_M397_HET",10];
_veh addItemCargoGlobal ["ACE_HuntIR_M203",10];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 10];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];