_veh = _this select 0;
_veh addItemCargoGlobal ["ACE_fieldDressing",30];
_veh addItemCargoGlobal ["ACE_packingBandage",25];
_veh addItemCargoGlobal ["ACE_elasticBandage",30];
_veh addItemCargoGlobal ["ACE_quikclot",30];
_veh addItemCargoGlobal ["ACE_morphine",30];
_veh addItemCargoGlobal ["ACE_epinephrine",15];
_veh addItemCargoGlobal ["ACE_bloodIV_500",10];
_veh addItemCargoGlobal ["ACE_plasmaIV_250",5];
_veh addItemCargoGlobal ["ACE_salineIV_250",5];
_veh addItemCargoGlobal ["ACE_personalAidKit",6];
_veh addItemCargoGlobal ["ACE_surgicalKit",3];