_veh = _this select 0;

_veh addItemcargoglobal ["rhs_30Rnd_762x39mm_tracer", 20]; 
_veh addItemcargoglobal ["rhs_30Rnd_762x39mm_89", 25];
_veh addItemcargoglobal ["rhs_100Rnd_762x54mmR", 10];
_veh addItemcargoglobal ["rhsgref_10Rnd_792x57_m76", 15];  
_veh addItemcargoglobal ["rhs_rpg7_PG7VL_mag", 2];
_veh addBackpackCargoGlobal ["rhs_r148",1];
_veh addItemCargoGlobal ["mkk_rhs_weap_rpg18",1];
_veh addItemcargoGlobal ["ACE_EarPlugs", 2];
_veh addItemcargoglobal ["rhs_mag_rgd5", 15];
_veh addItemcargoglobal ["rhs_VOG25", 15];  
_veh addItemcargoglobal ["rhs_mag_rdg2_white", 10];
_veh addItemcargoglobal ["ACE_morphine", 25]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 25]; 
_veh addItemCargoGlobal ["ACE_elasticBandage",25];
_veh addItemCargoGlobal ["ACE_packingBandage",25];
_veh addItemCargoGlobal ["ACE_quikclot",25];
_veh addItemCargoGlobal ["ACE_epinephrine",25];
_veh addBackpackCargoGlobal ["rhs_sidor",7];
_veh addItemcargoGlobal ["rhssaf_helmet_m59_85_nocamo", 2];
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope12",2];