_veh = _this select 0;

_veh addItemCargoGlobal ["rhs_mag_m67",15]; 
_veh addItemCargoGlobal ["rhs_mag_m18_purple",15]; 
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",5];
_veh addItemCargoGlobal ["rhsusf_200Rnd_556x45_box",5];
_veh addItemcargoGlobal ["rhsusf_20Rnd_762x51_SR25_m118_special_Mag",8];
_veh addItemcargoGlobal ["rhsusf_20Rnd_762x51_SR25_m62_Mag",5];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 10];
_veh addItemcargoglobal ["ACE_salineIV_500", 10]; 
_veh addItemcargoglobal ["ACE_bloodIV_500", 10];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemcargoglobal ["ACE_surgicalKit", 2]; 
_veh addItemcargoglobal ["ACE_personalAidKit", 2];
_veh addItemCargoGlobal ["rhs_mag_M585_white",25]; 
_veh addItemCargoGlobal ["ACE_Chemlight_HiBlue",40]; 
_veh addItemCargoGlobal ["B_IR_Grenade",40]; 