_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",25];
_veh addItemcargoGlobal ["ACE_epinephrine",25];
_veh addItemcargoGlobal ["ACE_fieldDressing",25]; 
_veh addItemcargoGlobal ["ACE_tourniquet",25];
_veh addItemcargoGlobal ["ACE_quikclot",25];
_veh addItemcargoGlobal ["ACE_suture",5];
_veh addItemcargoGlobal ["ACE_splint",5];
_veh addItemcargoGlobal ["ACE_elasticBandage",25];
_veh addItemcargoGlobal ["ACE_packingBandage", 25];
_veh addItemcargoGlobal ["ACE_personalAidKit",8];
_veh addItemcargoGlobal ["ACE_surgicalKit",2];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG",12];
_veh addItemcargoGlobal ["rhs_mag_100Rnd_556x45_Mk318_cmag",5];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",14];
_veh addItemcargoGlobal ["rhs_mag_m67",14];