_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",15];
_veh addItemcargoGlobal ["ACE_epinephrine",15];
_veh addItemcargoGlobal ["ACE_fieldDressing",15]; 
_veh addItemcargoGlobal ["ACE_tourniquet",8]; 
_veh addItemcargoGlobal ["ACE_quikclot",15];
_veh addItemcargoGlobal ["ACE_suture",2];
_veh addItemcargoGlobal ["ACE_splint",2];
_veh addItemcargoGlobal ["ACE_elasticBandage",15];
_veh addItemcargoGlobal ["ACE_packingBandage",15];
_veh addItemcargoGlobal ["ACE_personalAidKit",3];
_veh addItemcargoGlobal ["ACE_surgicalKit",1];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG",12];
_veh addItemcargoGlobal ["rhs_mag_100Rnd_556x45_Mk318_cmag",5];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",14];
_veh addItemcargoGlobal ["rhs_mag_m67",14];
_veh addItemcargoGlobal ["rhs_weap_M136",1];