_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",3];
_veh addItemcargoGlobal ["ACE_epinephrine",3];
_veh addItemcargoGlobal ["ACE_fieldDressing",6]; 
_veh addItemcargoGlobal ["ACE_tourniquet",3];
_veh addItemcargoGlobal ["ACE_suture",3];
_veh addItemcargoGlobal ["ACE_splint",3];
_veh addItemcargoGlobal ["ACE_quikclot",6];
_veh addItemcargoGlobal ["ACE_elasticBandage",6];
_veh addItemcargoGlobal ["ACE_packingBandage", 6];
_veh addItemcargoGlobal ["rhs_mag_m67",3];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",3];
_veh addItemcargoGlobal ["ToolKit", 1];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG",6];
_veh addItemcargoGlobal ["mkk_mag_M829A3",16];
_veh addItemcargoGlobal ["mkk_mag_M830A1",8];
_veh addItemcargoGlobal ["mkk_mag_M1069",8];
_veh addItemcargoGlobal ["ace_mag_100rnd_127x99_mag_Tracer_Red",10];
_veh addItemcargoGlobal ["rhsusf_100Rnd_762x51_m80a1epr",12];
