_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",22];
_veh addItemcargoGlobal ["ACE_epinephrine",22];
_veh addItemcargoGlobal ["ACE_fieldDressing",22]; 
_veh addItemcargoGlobal ["ACE_tourniquet",22]; 
_veh addItemcargoGlobal ["ACE_quikclot",22];
_veh addItemcargoGlobal ["ACE_elasticBandage",22];
_veh addItemcargoGlobal ["ACE_packingBandage", 22];
_veh addItemcargoGlobal ["ACE_personalAidKit",5];
_veh addItemcargoGlobal ["ACE_surgicalKit",5];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG",20];
_veh addItemcargoGlobal ["rhs_mag_100Rnd_556x45_Mk318_cmag",5];
_veh addItemcargoGlobal ["rhsusf_200rnd_556x45_mixed_box",5];
_veh addItemcargoGlobal ["rhs_weap_M136",2];
_veh addItemcargoGlobal ["rhs_weap_M136_hedp",1];
_veh addItemcargoGlobal ["rhs_mag_M433_HEDP",8];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",14];
_veh addItemcargoGlobal ["rhs_mag_m67",14];
_veh addItemcargoGlobal ["rhsusf_20Rnd_762x51_SR25_m993_Mag",10];