_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",4];
_veh addItemcargoGlobal ["ACE_epinephrine",4];
_veh addItemcargoGlobal ["ACE_fieldDressing",8]; 
_veh addItemcargoGlobal ["ACE_tourniquet",4];
_veh addItemcargoGlobal ["ACE_suture",2];
_veh addItemcargoGlobal ["ACE_splint",2];
_veh addItemcargoGlobal ["ACE_quikclot",8];
_veh addItemcargoGlobal ["ACE_elasticBandage",8];
_veh addItemcargoGlobal ["ACE_packingBandage", 8];
_veh addItemcargoGlobal ["rhs_mag_f1",4];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",4];
_veh addItemcargoGlobal ["rhs_30Rnd_545x39_7N10_AK",8];
_veh addItemcargoGlobal ["rhs_30Rnd_762x39mm_89",8];
_veh addItemcargoGlobal ["ACE_rope6", 1];
_veh addItemcargoGlobal ["ACE_rope12", 1];
_veh addItemcargoGlobal ["ToolKit", 3];
_veh addBackpackCargoGlobal ["rhs_sidor", 3];