_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",4];
_veh addItemcargoGlobal ["ACE_epinephrine",4];
_veh addItemcargoGlobal ["ACE_fieldDressing",4]; 
_veh addItemcargoGlobal ["ACE_tourniquet",4]; 
_veh addItemcargoGlobal ["ACE_quikclot",4];
_veh addItemcargoGlobal ["ACE_suture",2];
_veh addItemcargoGlobal ["ACE_splint",2];
_veh addItemcargoGlobal ["ACE_elasticBandage",4];
_veh addItemcargoGlobal ["ACE_packingBandage", 4];
_veh addItemcargoGlobal ["rhs_mag_f1",2];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",2];
_veh addItemcargoGlobal ["rhs_30Rnd_545x39_7N10_AK",4];
_veh addItemcargoGlobal ["rhs_30Rnd_762x39mm_89",4];
_veh addItemcargoGlobal ["ACE_rope6", 1];
_veh addItemcargoGlobal ["ToolKit", 1];
_veh addItemcargoGlobal ["ACE_rope12", 1];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",10];
_veh addItemCargoGlobal ["ace_mag_127x108mm_50",5];
_veh addItemCargoGlobal ["ace_1Rnd_152mm_of53",52];
