_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",15];
_veh addItemcargoGlobal ["ACE_epinephrine",15];
_veh addItemcargoGlobal ["ACE_fieldDressing",15]; 
_veh addItemcargoGlobal ["ACE_tourniquet",8]; 
_veh addItemcargoGlobal ["ACE_quikclot",15];
_veh addItemcargoGlobal ["ACE_elasticBandage",15];
_veh addItemcargoGlobal ["ACE_suture",2];
_veh addItemcargoGlobal ["ACE_splint",2];
_veh addItemcargoGlobal ["ACE_packingBandage",15];
_veh addItemcargoGlobal ["ACE_personalAidKit",3];
_veh addItemcargoGlobal ["ACE_surgicalKit",1];
_veh addItemcargoGlobal ["rhs_mag_f1",12];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",12];
_veh addItemcargoGlobal ["rhs_30Rnd_545x39_7N10_AK",14];
_veh addItemcargoGlobal ["rhs_30Rnd_762x39mm_89",14];
_veh addItemcargoGlobal ["mkk_20Rnd_762x51_m80a1_Mag",10];
_veh addItemcargoGlobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemcargoGlobal ["nmg_96Rnd_545x39_7N10_RPK16",5];
_veh addItemcargoGlobal ["ToolKit", 1];
_veh addItemcargoGlobal ["rhs_VOG25",14];
_veh addItemcargoGlobal ["rhs_weap_rpg26",1];
_veh addItemcargoGlobal ["rhs_weap_rshg2",1];
_veh addItemcargoGlobal ["ACE_rope6", 1];
_veh addItemcargoGlobal ["ACE_rope12", 1];
_veh addItemcargoGlobal ["mkkc_armst_rg6", 1];
_veh addItemcargoGlobal ["mkkc_6x_vog25", 6];
_veh addItemCargoGlobal ["ace_mag_9m1331_tdh",4];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",10];
