_veh = _this select 0;
_veh addItemCargoGlobal ["ACE_fieldDressing",10];
_veh addItemCargoGlobal ["ACE_elasticBandage",10];
_veh addItemCargoGlobal ["ACE_packingBandage",10];
_veh addItemCargoGlobal ["ACE_quikclot",10];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh additemcargoGlobal ["ACE_tourniquet",10];
_veh additemcargoGlobal ["nmg_30Rnd_545x39_7N10_AK12",30];
_veh additemcargoGlobal ["nmg_30Rnd_545x39_7T3M_AK12",5];
_veh additemcargoGlobal ["rhs_10Rnd_762x54mmR_7N14",6];
_veh additemcargoGlobal ["vtn_pg7vm",4];
_veh additemcargoGlobal ["vtn_og7v",4];
_veh additemcargoGlobal ["rhs_mag_rgd5",10];
_veh additemcargoGlobal ["rhs_mag_rdg2_white",10];
_veh additemcargoGlobal ["rhs_100Rnd_762x54mmR_7N26",5];
_veh addMagazinecargoglobal ["rhs_VOG25", 40]; 
_veh addItemCargoGlobal ["ACE_rope6",2];
_veh addItemCargoGlobal ["ACE_rope18",2];
_veh addItemCargoGlobal ["ACE_splint",10];
_veh addMagazineTurret ["rhs_mag_127x108mm_150",[0]];
