_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addWeaponcargoglobal ["rhs_weap_rshg2", 1];
_veh addWeaponcargoglobal ["rhsusf_acc_anpas13gv1", 2];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_bakelite_89",40];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_bakelite_tracer",20];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",10];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR_7N26",10];
_veh addItemCargoGlobal ["rhs_VOG25",25];
_veh addItemCargoGlobal ["H_Cap_headphones",1];
_veh addItemCargoGlobal ["rhs_mag_rgd5",20];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white",20];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",20];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];