_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",12];
_veh addItemcargoGlobal ["ACE_epinephrine",12];
_veh addItemcargoGlobal ["ACE_fieldDressing",12]; 
_veh addItemcargoGlobal ["ACE_tourniquet",12]; 
_veh addItemcargoGlobal ["ACE_quikclot",12];
_veh addItemcargoGlobal ["ACE_elasticBandage",12];
_veh addItemcargoGlobal ["ACE_packingBandage", 12];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_PMAG",6];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",6];
_veh addItemcargoGlobal ["rhs_mag_M829A3",16];
_veh addItemcargoGlobal ["rhs_mag_M830A1",8];
_veh addItemcargoGlobal ["rhs_mag_M1069",8];
_veh addItemcargoGlobal ["rhs_mag_762x51_M240_1200",4];
_veh addItemcargoGlobal ["ace_mag_100rnd_127x99_mag_Tracer_Red",6];
_veh addItemcargoGlobal ["rhs_mag_762x51_M240_200",2];
_veh addItemcargoGlobal ["rhs_mag_m67",6];
