_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_m136", 3];
_veh addItemcargoglobal ["rhs_mag_m67",10];
_veh addItemcargoglobal ["rhs_mag_an_m8hc",10];
_veh addItemcargoglobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",10];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 10];
_veh addItemcargoglobal ["ACE_tourniquet", 10];
_veh addItemCargoGlobal ["ToolKit",1];
_veh addItemcargoglobal ["rhsusf_ach_helmet_ocp",4];
_veh addMagazinecargoglobal ["rhs_mag_M829A3", 22];
_veh addMagazinecargoglobal ["rhs_mag_M830A1", 8];
_veh addMagazinecargoglobal ["rhs_mag_M1069", 10];
_veh addMagazinecargoglobal ["rhs_mag_762x51_M240_1200", 8];
_veh addMagazinecargoglobal ["rhs_mag_762x51_M240_200", 9];
_veh addMagazinecargoglobal ["ace_mag_100rnd_127x99_mag_Tracer_Red", 10];