_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",12];
_veh addItemcargoGlobal ["ACE_epinephrine",12];
_veh addItemcargoGlobal ["ACE_fieldDressing",12]; 
_veh addItemcargoGlobal ["ACE_tourniquet",12]; 
_veh addItemcargoGlobal ["ACE_quikclot",12];
_veh addItemcargoGlobal ["ACE_elasticBandage",12];
_veh addItemcargoGlobal ["ACE_packingBandage", 12];
_veh addItemcargoGlobal ["ACE_personalAidKit",12];
_veh addItemcargoGlobal ["rhs_mag_m67",8];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",8];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",12];
_veh addItemcargoGlobal ["mkk_20Rnd_M80A1_762x51_HK417",10];
_veh addItemcargoGlobal ["rhs_mag_20Rnd_SCAR_762x51_m61_ap",10];
_veh addItemcargoGlobal ["DemoCharge_Remote_Mag",1];
_veh addItemcargoGlobal ["SatchelCharge_Remote_Mag",1];
_veh addItemcargoGlobal ["ACE_Clacker",2];