_veh = _this select 0;
_veh addItemcargoGlobal ["ACE_morphine",12];
_veh addItemcargoGlobal ["ACE_epinephrine",12];
_veh addItemcargoGlobal ["ACE_fieldDressing",12]; 
_veh addItemcargoGlobal ["ACE_tourniquet",12]; 
_veh addItemcargoGlobal ["ACE_quikclot",12];
_veh addItemcargoGlobal ["ACE_elasticBandage",12];
_veh addItemcargoGlobal ["ACE_packingBandage", 12];
_veh addItemcargoGlobal ["ACE_personalAidKit",12];
_veh addItemcargoGlobal ["rhs_mag_m67",3];
_veh addItemcargoGlobal ["rhs_mag_an_m8hc",3];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",6];
