_veh = _this select 0;
_veh addItemcargoglobal ["ACE_quikclot", 10]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 10]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 10]; 
_veh addItemcargoglobal ["ACE_epinephrine", 3];
_veh addItemcargoglobal ["ACE_packingBandage", 10];
_veh addItemcargoglobal ["ACE_morphine", 3];
_veh addItemcargoglobal ["ACE_tourniquet", 3];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",10];
_veh addItemCargoGlobal ["ToolKit",1];
_veh addBackpackCargoGlobal ["usm_pack_alice", 1];
