_veh = _this select 0;

_veh addWeaponcargoglobal ["rhs_weap_rpg26", 1];
_veh addWeaponcargoglobal ["rhs_weap_rshg2", 1];
_veh addItemCargoGlobal ["rhs_mag_rdg2_white", 20];
_veh addItemCargoGlobal ["rhs_mag_rgd5", 10];
_veh addItemCargoGlobal ["rhs_mag_rgn", 10];
_veh addItemCargoGlobal ["rhs_VOG25", 25];
_veh addItemCargoGlobal ["rhs_VOG25P", 10];
_veh addItemCargoGlobal ["rhs_GRD40_White",10];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR",5];
_veh addItemCargoGlobal ["rhs_100Rnd_762x54mmR_green",5];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_polymer_89",20];
_veh addItemCargoGlobal ["rhs_30Rnd_762x39mm_polymer_tracer",20];
_veh addItemCargoGlobal ["rhs_10Rnd_762x54mmR_7N14",10];
_veh addItemcargoglobal ["ACE_quikclot", 20]; 
_veh addItemcargoglobal ["ACE_elasticBandage", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 20]; 
_veh addItemcargoglobal ["ACE_epinephrine", 20];
_veh addItemcargoglobal ["ACE_packingBandage", 20];
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemcargoglobal ["ACE_tourniquet", 10];