_veh = _this select 0;

_veh addItemCargoGlobal ["ACE_tourniquet",5];
_veh addItemCargoGlobal ["ACE_fieldDressing",15];
_veh addItemCargoGlobal ["ACE_elasticBandage",15];
_veh addItemCargoGlobal ["ACE_packingBandage",15];
_veh addItemCargoGlobal ["ACE_quikclot",15];
_veh addItemCargoGlobal ["ACE_morphine",10];
_veh addItemCargoGlobal ["ACE_epinephrine",10];
_veh addItemCargoGlobal ["ACE_EarPlugs",4];
_veh addItemCargoGlobal ["rhs_mag_m67",8];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",6];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",12];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",6];
_veh addItemCargoGlobal ["ToolKit",1];
_veh addBackpackCargoGlobal ["mkk_B_Predator_MTP",1];
_veh addItemCargoGlobal ["mkk_H_BAF_MTP_Mk6_NETTING_PRR", 4];
_veh addMagazinecargoglobal ["mkk_125mm_SABOT_MAG", 20]; 
_veh addMagazinecargoglobal ["mkk_125mm_HESH_MAG", 8]; 
_veh addItemCargoGlobal ["rhs_mag_762x51_M240_1200",1];