_veh = _this select 0;
_veh addItemCargoGlobal ["ACE_fieldDressing",50];
_veh addItemCargoGlobal ["ACE_packingBandage",45];
_veh addItemCargoGlobal ["ACE_elasticBandage",40];
_veh addItemCargoGlobal ["ACE_quikclot",40];
_veh addItemCargoGlobal ["ACE_morphine",40];
_veh addItemCargoGlobal ["ACE_epinephrine",15];
_veh addItemCargoGlobal ["ACE_bloodIV_500",20];
_veh addItemCargoGlobal ["ACE_plasmaIV_250",8];
_veh addItemCargoGlobal ["ACE_salineIV_250",8];
_veh addItemCargoGlobal ["ACE_tourniquet",8];
_veh addItemCargoGlobal ["ACE_personalAidKit",20];
_veh addItemCargoGlobal ["ACE_surgicalKit",4];
_veh addItemCargoGlobal ["rhs_mag_m67",12];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",2];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",20];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",14];
_veh addItemCargoGlobal ["ace_48Rnd_40mm_MK19_M430A1",2];