_veh = _this select 0;
this disableTIEquipment true; 
_veh addItemCargoGlobal ["ACE_tourniquet",8];
_veh addItemCargoGlobal ["ACE_fieldDressing",8];
_veh addItemCargoGlobal ["ACE_elasticBandage",8];
_veh addItemCargoGlobal ["ACE_packingBandage",8];
_veh addItemCargoGlobal ["ACE_quikclot",8];
_veh addItemCargoGlobal ["ACE_morphine",8];
_veh addItemCargoGlobal ["ACE_epinephrine",8];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",10];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", 6];
_veh addItemCargoGlobal ["rhs_mag_m67",6];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",6];
_veh addItemCargoGlobal ["rhsusf_ach_helmet_ocp",2];
_veh addBackpackCargoGlobal ["B_Parachute", 2];
