_veh = _this select 0;

_veh addItemCargoGlobal ["rhsusf_ach_helmet_ucp_alt",3];
_veh addItemCargoGlobal ["ACE_tourniquet",5];
_veh addItemCargoGlobal ["ACE_fieldDressing",12];
_veh addItemCargoGlobal ["ACE_elasticBandage",12];
_veh addItemCargoGlobal ["ACE_packingBandage",12];
_veh addItemCargoGlobal ["ACE_quikclot",12];
_veh addItemCargoGlobal ["ACE_morphine",8];
_veh addItemCargoGlobal ["ACE_epinephrine",8];
_veh addItemCargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag",8];
_veh addItemcargoGlobal ["rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", 4];
_veh addItemCargoGlobal ["rhsusf_mag_10Rnd_STD_50BMG_M33",10];
_veh addItemCargoGlobal ["rhsusf_mag_10Rnd_STD_50BMG_mk211",5];
_veh addItemCargoGlobal ["ACE_5Rnd_127x99_API_Mag",5];
_veh addItemCargoGlobal ["ACE_5Rnd_127x99_AMAX_Mag",5];
_veh addItemCargoGlobal ["rhsusf_20Rnd_762x51_m118_special_Mag",15];
_veh addItemCargoGlobal ["rhsusf_mag_17Rnd_9x19_JHP",8];
_veh addItemCargoGlobal ["rhs_mag_m67",10];
_veh addItemCargoGlobal ["rhs_mag_an_m8hc",10];
_veh addItemCargoGlobal ["ACE_Tripod",2];