_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_7N10_AK", 10];
		_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_AK_green", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_m67", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_f1", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_m18_purple", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_m18_yellow", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_m18_red", 5];
		_veh addBackpackCargoGlobal ["B_TacticalPack_blk", 1];
		_veh addItemCargoGlobal ["ACE_fieldDressing",20];
		_veh addItemCargoGlobal ["ACE_quikclot",15];
		_veh addItemCargoGlobal ["ACE_elasticBandage",20];
		_veh addItemCargoGlobal ["ACE_packingBandage",20];
		_veh addItemCargoGlobal ["ACE_tourniquet",5];
		_veh addItemCargoGlobal ["ACE_morphine",20];
		_veh addItemCargoGlobal ["ACE_epinephrine",15];
		_veh addItemCargoGlobal ["ACE_atropine",10];
		_veh addItemCargoGlobal ["ACE_salineIV",7];
		_veh addItemCargoGlobal ["ACE_bloodIV",7];
		_veh addItemCargoGlobal ["ACE_plasmaIV",7];
		_veh addItemCargoGlobal ["ACE_personalAidKit",10];