_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_7N10_AK", 10];
		_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_AK_green", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_rgd5", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_f1", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_m18_purple", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_m18_yellow", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_m18_red", 5];
		_veh addBackpackCargoGlobal ["B_TacticalPack_oli", 2];
		_veh addItemCargoGlobal ["ACE_fieldDressing",6];
		_veh addItemCargoGlobal ["ACE_quikclot",6];
		_veh addItemCargoGlobal ["ACE_elasticBandage",6];
		_veh addItemCargoGlobal ["ACE_packingBandage",6];
		_veh addItemCargoGlobal ["ACE_tourniquet",6];
		_veh addItemCargoGlobal ["ACE_morphine",4];
		_veh addItemCargoGlobal ["ACE_epinephrine",3];