_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_7N10_AK", 10];
_veh addMagazineCargoGlobal ["rhs_mag_rgd5", 5];
_veh addMagazineCargoGlobal ["rhs_mag_m18_purple", 5];
_veh addBackpackCargoGlobal ["B_TacticalPack_oli", 3];
		_veh addItemCargoGlobal ["ACE_fieldDressing",5];
		_veh addItemCargoGlobal ["ACE_quikclot",5];
		_veh addItemCargoGlobal ["ACE_elasticBandage",5];
		_veh addItemCargoGlobal ["ACE_packingBandage",5];
		_veh addItemcargoglobal ["ToolKit", 1];
		_veh addItemCargoGlobal ["ACE_tourniquet",3];
		_veh addItemCargoGlobal ["ACE_morphine",3];
		_veh addItemCargoGlobal ["ACE_epinephrine",3];
		_veh addItemCargoGlobal ["rhsgref_ssh68_ttsko_mountain",3];