_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_7N10_AK", 30];
		_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_AK_green", 10];
		_veh addMagazineCargoGlobal ["mkk_VTN_RPK74_45p_SC", 10];
			_veh addMagazineCargoGlobal ["mkk_VTN_RPK74_45p_SC", 10];
		_veh addMagazineCargoGlobal ["rhs_100Rnd_762x54mmR", 5];
		_veh addMagazineCargoGlobal ["rhs_10Rnd_762x54mmR_7N14", 5];
		_veh addMagazineCargoGlobal ["rhs_GDM40", 5];
		_veh addMagazineCargoGlobal ["rhs_GRD40_White", 2];
		_veh addMagazineCargoGlobal ["rhs_GRD40_Green", 2];
		_veh addMagazineCargoGlobal ["rhs_GRD40_Red", 2];
		_veh addMagazineCargoGlobal ["rhs_mag_m67", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_f1", 10];
		_veh addMagazineCargoGlobal ["rhs_mag_m18_purple", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_m18_yellow", 5];
		_veh addMagazineCargoGlobal ["rhs_mag_m18_red", 5];
		_veh addBackpackCargoGlobal ["B_TacticalPack_blk", 2];
		_veh addWeaponCargoGlobal ["rhs_weap_rpg26", 1];
		_veh addItemCargoGlobal ["ACE_fieldDressing",15];
		_veh addItemCargoGlobal ["ACE_quikclot",15];
		_veh addItemCargoGlobal ["ACE_elasticBandage",15];
		_veh addItemCargoGlobal ["ACE_packingBandage",5];
		_veh addItemCargoGlobal ["ACE_tourniquet",8];
		_veh addItemCargoGlobal ["ACE_morphine",15];
		_veh addItemCargoGlobal ["ACE_epinephrine",15];