_veh = _this select 0;

_veh addItemcargoGlobal ["ACE_bloodIV_500",8];
_veh addItemcargoGlobal ["ACE_morphine",12];
_veh addItemcargoGlobal ["ACE_epinephrine",12];
_veh addItemcargoGlobal ["ACE_fieldDressing",20]; 
_veh addItemcargoGlobal ["ACE_tourniquet",4]; 
_veh addItemcargoGlobal ["ACE_personalAidKit",4];
_veh addItemcargoGlobal ["ACE_surgicalKit",2];
_veh addItemcargoGlobal ["ACE_quikclot",10];
_veh addItemcargoGlobal ["ACE_elasticBandage",10];
_veh addItemcargoGlobal ["ACE_packingBandage", 10]; 
_veh addItemcargoglobal ["rhs_30Rnd_545x39_7N10_AK", 25]; 
_veh addItemcargoglobal ["rhs_30Rnd_545x39_AK_green", 10]; 
_veh addItemcargoglobal ["rhs_100Rnd_762x54mmR", 5]; 
_veh addItemcargoglobal ["rhs_10Rnd_762x54mmR_7N14", 5];  
_veh addItemCargoGlobal ["rhs_mag_rgd5", 7];  
_veh addItemCargoGlobal ["rhs_mag_rdg2_white", 7];
_veh addItemCargoGlobal ["ACE_rope6", 1];  
_veh addItemCargoGlobal ["ACE_rope12", 1]; 
_veh addItemcargoglobal ["vtn_pg7v", 2]; 
_veh addItemcargoglobal ["vtn_og7v", 1]; 
_veh addBackpackCargoGlobal ["rhs_sidor", 1];